//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPA02
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight_data
    {
        public int id { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<System.DateTime> departure_time { get; set; }
        public Nullable<System.DateTime> arrival_time { get; set; }
        public Nullable<int> layover { get; set; }
        public Nullable<int> remaining_tickets { get; set; }
    }
}
